# Generated by Django 2.2.5 on 2019-09-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='image',
            field=models.ImageField(upload_to='toppings/'),
        ),
    ]
